In [1]:
# Perform association rule mining to the data and identify significant rules with support ≥ 0.01 and confidence ≥ 0.5
## import packages

import pandas as pd

# On my pc CSV file is not imported properly (only 3051 lines)
import csv

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
## Read the csv file & import into 'lines' array

file = open('./store_data.csv', 'r')

lines = []

i = 0


"""

# ---> FIRST TRY (did not work for me because only 3751 lines are appended)

while file.readline():
    i = i + 1
    lines.append(file.readline().strip().split(','))


# ---> SECOND TRY 2 (did not work for me because only 3572 lines are appended)

while True:
    line = file.readline()
    i = i + 1
    if not line:
        break
    lines.append(file.readline().strip().split(','))

"""

# ---> THIRD TRY (ONLY OPTION 3 worked) --> 

csvreader = csv.reader(file)

for line in csvreader:
    lines.append(line)
    
    # test to check number of appended lines
    i = i + 1
    

display(i)

7501

In [3]:
## Transform the data

te = TransactionEncoder()
te_arr = te.fit_transform(lines)
df = pd.DataFrame(te_arr, columns=te.columns_)
df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [4]:
# Identify significant rules with support ≥ 0.01

frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)
frequent_itemsets

      support                                 itemsets
0    0.020397                                (almonds)
1    0.033329                                (avocado)
2    0.010799                         (barbecue sauce)
3    0.014265                              (black tea)
4    0.011465                             (body spray)
..        ...                                      ...
252  0.011065       (ground beef, mineral water, milk)
253  0.017064  (ground beef, spaghetti, mineral water)
254  0.015731         (spaghetti, mineral water, milk)
255  0.010265    (olive oil, spaghetti, mineral water)
256  0.011465     (pancakes, spaghetti, mineral water)

[257 rows x 2 columns]

In [5]:
## Identify significant rules with confidence ≥ 0.5

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(ground beef, eggs)",(mineral water),0.019997,0.238368,0.010132,0.506667,2.125563,0.005365,1.543848
1,"(ground beef, milk)",(mineral water),0.021997,0.238368,0.011065,0.503030,2.110308,0.005822,1.532552